/**
 * Guards the generated OpenAPI types and the aliases `lib/api.ts` derives from
 * them.
 *
 * Two failure modes this pins down:
 *
 * 1. **Regenerating from the wrong spec.** `web/app.py` hides every route and
 *    then re-enables a 16-entry `_PUBLIC_API` allowlist, so the published
 *    `docs/openapi.json` carries only 12 paths. `src/lib/api-generated.ts` has
 *    to come from `scripts/export_openapi.py --internal` (~350 paths) or every
 *    alias in `api.ts` loses its schema. The marker assertions below fail if
 *    someone regenerates from the public spec.
 *
 * 2. **Re-hand-writing a migrated type.** `expectTypeOf(...).toEqualTypeOf(...)`
 *    is erased at runtime but checked by `tsc`, so replacing an alias with a
 *    hand-written interface — the drift this file exists to prevent — fails the
 *    type check rather than waiting to surface as `undefined` in the UI.
 *
 * Regenerate with `pnpm gen:api:export && pnpm gen:api` (see CONTRIBUTING.md).
 */
import { readFileSync } from "node:fs"
import path from "node:path"

import { describe, expect, expectTypeOf, it } from "vitest"

// Type-only imports: `lib/api.ts` has module-level state, and this test only
// needs its types.
import type {
  AdminActiveSession,
  AdminAnnouncement,
  AdminCredentialStats,
  AdminLoginStats,
  AdminNotificationConfig,
  AdminSensitiveWord,
  AdminTrendEntry,
  AdminUsageEntry,
  ConnectorStats,
  DashboardAgent,
  DashboardConnectorHealth,
  DashboardConversation,
  DashboardDayStat,
  DashboardKB,
  DashboardStats,
  DashboardWorkflowRun,
} from "../api"
import type { components, paths } from "../api-generated"

// Same resolution style as lib/__tests__/motion.test.ts.
const generated = readFileSync(
  path.resolve(__dirname, "../api-generated.ts"),
  "utf8",
)

describe("api-generated.ts", () => {
  it("carries the generator banner", () => {
    expect(generated).toContain("auto-generated by openapi-typescript")
  })

  it("exports the openapi-typescript namespaces", () => {
    expect(generated).toContain("export interface paths {")
    expect(generated).toContain("export interface components {")
    expect(generated).toContain("export interface operations {")
  })

  it("was generated from the internal spec, not the public allowlist", () => {
    // Present only when every route is exported. The public spec has none of
    // these: /api/admin/* is outside the _PUBLIC_API allowlist, and
    // LoginStatsResponse / DashboardStatsResponse are internal response models.
    expect(generated).toContain('"/api/admin/analytics/by-agent"')
    expect(generated).toContain("LoginStatsResponse:")
    expect(generated).toContain("DashboardStatsResponse:")
  })
})

describe("paths", () => {
  it("types the dashboard stats endpoint end to end", () => {
    expectTypeOf<
      paths["/api/dashboard/stats"]["get"]["responses"][200]
    >().not.toBeNever()
  })
})

describe("api.ts aliases stay spec-derived", () => {
  it("dashboard types", () => {
    expectTypeOf<DashboardStats>().toEqualTypeOf<
      components["schemas"]["DashboardStatsResponse"]
    >()
    expectTypeOf<DashboardConversation>().toEqualTypeOf<
      components["schemas"]["DashboardConversation"]
    >()
    expectTypeOf<DashboardAgent>().toEqualTypeOf<components["schemas"]["DashboardAgent"]>()
    expectTypeOf<DashboardKB>().toEqualTypeOf<components["schemas"]["DashboardKB"]>()
    expectTypeOf<DashboardConnectorHealth>().toEqualTypeOf<
      components["schemas"]["DashboardConnectorHealth"]
    >()
    expectTypeOf<DashboardDayStat>().toEqualTypeOf<components["schemas"]["DashboardDayStat"]>()
    expectTypeOf<DashboardWorkflowRun>().toEqualTypeOf<
      components["schemas"]["DashboardWorkflowRun"]
    >()
  })

  it("admin types", () => {
    expectTypeOf<AdminLoginStats>().toEqualTypeOf<components["schemas"]["LoginStatsResponse"]>()
    expectTypeOf<AdminActiveSession>().toEqualTypeOf<
      components["schemas"]["ActiveSessionItem"]
    >()
    expectTypeOf<AdminAnnouncement>().toEqualTypeOf<components["schemas"]["AnnouncementInfo"]>()
    expectTypeOf<AdminCredentialStats>().toEqualTypeOf<
      components["schemas"]["CredentialStatsResponse"]
    >()
    expectTypeOf<AdminNotificationConfig>().toEqualTypeOf<
      components["schemas"]["NotificationConfig"]
    >()
    expectTypeOf<AdminSensitiveWord>().toEqualTypeOf<
      components["schemas"]["SensitiveWordInfo"]
    >()
    expectTypeOf<AdminUsageEntry>().toEqualTypeOf<components["schemas"]["UserTokenUsage"]>()
    expectTypeOf<AdminTrendEntry>().toEqualTypeOf<components["schemas"]["DailyTrend"]>()
    expectTypeOf<ConnectorStats>().toEqualTypeOf<
      components["schemas"]["ConnectorStatsResponse"]
    >()
  })
})
